#ifndef PARAMETERS_H
#define PARAMETERS_H


#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define PADDLE_HEIGHT (WINDOW_HEIGHT / 6.0)
#define PADDLE_WIDTH (WINDOW_WIDTH / 80.0)
#define BALL_SIZE (PADDLE_HEIGHT / 10.0)
#define BALL_SPEED 0.01
#define PLAYER_VELOCITY_DELTA 0.05


#endif // PARAMETERS_H
